"""Sync user columns

Revision ID: 1832c5ca3bc0
Revises: b7b1a88f311d
Create Date: 2026-06-15 15:51:08.803900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1832c5ca3bc0'
down_revision: Union[str, Sequence[str], None] = 'b7b1a88f311d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_picture_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('is_email_verified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('has_password', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('otp_code', sa.String(length=6), nullable=True))
    op.add_column('users', sa.Column('otp_expires_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('otp_attempts', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('login_attempts', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('lockout_until', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lockout_until')
    op.drop_column('users', 'login_attempts')
    op.drop_column('users', 'otp_attempts')
    op.drop_column('users', 'otp_expires_at')
    op.drop_column('users', 'otp_code')
    op.drop_column('users', 'has_password')
    op.drop_column('users', 'is_email_verified')
    op.drop_column('users', 'profile_picture_url')
    # ### end Alembic commands ###
