"""add_contact_reply_fields

Revision ID: dad0d187c0fc
Revises: 1832c5ca3bc0
Create Date: 2026-06-24 11:04:46.973252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dad0d187c0fc'
down_revision: Union[str, Sequence[str], None] = '1832c5ca3bc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_messages', sa.Column('reply_message', sa.Text(), nullable=True))
    op.add_column('contact_messages', sa.Column('replied_at', sa.DateTime(), nullable=True))
    op.add_column('contact_messages', sa.Column('is_replied', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact_messages', 'is_replied')
    op.drop_column('contact_messages', 'replied_at')
    op.drop_column('contact_messages', 'reply_message')
    # ### end Alembic commands ###
